export const CHAT_ERROR_CODES = {
  INVALID_INPUT: 'INVALID_INPUT',
  ACCESS_TOKEN_MISSING: 'ACCESS_TOKEN_MISSING',
  INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
  EXPIRED_ACCESS_TOKEN: 'EXPIRED_ACCESS_TOKEN',
  CLIENT_STATE_INVALID: 'CLIENT_STATE_INVALID',
  MESSAGE_SEND_FAILED: 'MESSAGE_SEND_FAILED',
  FORBIDDEN_CHANNEL: 'FORBIDDEN_CHANNEL',

  TARGET_OFFLINE: 'TARGET_OFFLINE',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  YOU_ARE_BLOCKED: 'YOU_ARE_BLOCKED',
  TARGET_IS_BLOCKED: 'TARGET_IS_BLOCKED',
  CANNOT_WHISPER_SELF: 'CANNOT_WHISPER_SELF',
  NOT_FRIENDS: 'NOT_FRIENDS',
} as const;
